//! # Clinical Alert Override Rate
//!
//! Clinical alert override rate measures the share of clinical decision
//! support (CDS) alerts — such as drug-drug interaction warnings, allergy
//! alerts, and dose-range checks generated by a computerized provider order
//! entry (CPOE) system — that a clinician dismisses or overrides rather than
//! acts on. It is the standard quantitative signal used to detect and manage
//! "alert fatigue": the well-documented tendency for clinicians to become
//! desensitized to alerts once the volume of low-value warnings becomes
//! overwhelming.
//!
//! ## How it's calculated
//!
//! ```text
//! Override rate = alerts overridden / total alerts fired × 100
//!
//! Segment by:
//!   - severity tier (e.g. contraindicated, major, moderate)
//!   - alert type (drug-drug interaction, allergy, duplicate therapy, dose range)
//!   - whether an override reason was documented
//!
//! A "documented override rate" tracks the share of overrides that carry a
//! recorded justification, which is a governance measure in its own right.
//! ```
//!
//! ## Why it matters
//!
//! Published override rates for drug interaction alerts commonly range from
//! roughly half to over ninety percent, and a high rate is not automatically
//! a safety failure: many interruptive alerts fire for interactions that are
//! clinically insignificant in context, so a well-tuned system deliberately
//! fires fewer, higher-value alerts rather than trying to drive the override
//! rate to zero. What genuinely matters for safety is the trend over time,
//! the distribution across severity tiers, and whether clinicians document a
//! reason when they override a high-severity alert.
//!
//! ## Worked example
//!
//! A hospital's CPOE system fires 10,000 drug-drug interaction alerts in a
//! month, of which 8,700 are overridden. Segmenting by severity shows that
//! of 500 "contraindicated" alerts, 60 are overridden, while of 6,000
//! "moderate" alerts, 5,700 are overridden. The moderate-tier figure is
//! broadly consistent with published benchmarks; the contraindicated-tier
//! figure warrants individual case review, and the fact that only a minority
//! of those overrides carry a documented reason is the more actionable
//! governance finding.
//!
//! ```rust
//! use digital_health::clinical_alert_override_rate::{override_rate, documented_override_rate};
//!
//! // Overall: 8,700 / 10,000 × 100 = 87%.
//! let overall = override_rate(8_700.0, 10_000.0).unwrap();
//! assert!((overall - 87.0).abs() < 1e-9);
//!
//! // Contraindicated tier: 60 / 500 × 100 = 12% — warrants individual case review.
//! let contraindicated = override_rate(60.0, 500.0).unwrap();
//! assert!((contraindicated - 12.0).abs() < 1e-9);
//!
//! // Moderate tier: 5,700 / 6,000 × 100 = 95% — consistent with published benchmarks.
//! let moderate = override_rate(5_700.0, 6_000.0).unwrap();
//! assert!((moderate - 95.0).abs() < 1e-9);
//!
//! // Documented-reason rate on the overrides that most need scrutiny.
//! let documented = documented_override_rate(340.0, 500.0).unwrap();
//! assert!((documented - 68.0).abs() < 1e-9);
//! ```
//!
//! ## Data sources and caveats
//!
//! The electronic health record's audit log, or the CDS vendor's own
//! alerting module, records each alert-fired and alert-response event,
//! including whether the clinician entered a justification. Comparing
//! override rates between organizations requires checking that the
//! underlying alert rule sets and severity tiering are the same.
//!
//! ## Pitfalls
//!
//! - **Treating the raw override rate as a single safety score** — it
//!   conflates well-justified overrides of low-value alerts with unsafe
//!   overrides of genuinely dangerous interactions; always segment by
//!   severity.
//! - **No override-reason capture** — without a documented reason, it is
//!   impossible to distinguish "this alert was wrong" from "this alert was
//!   right and the clinician made an unsafe judgement call".
//! - **Alert-rule inflation over time** — adding more alerts without pruning
//!   low-value ones is the direct cause of rising override rates.
//! - **Comparing rates across systems with different interruption design** —
//!   an interruptive, hard-stop alert produces different override behaviour
//!   from a passive, non-blocking one.
//!
//! ## Sources
//!
//! - Peer-reviewed literature on clinical decision support alert fatigue,
//!   widely published in journals including JAMIA and npj Digital Medicine.
//! - ONC / HealthIT.gov, health IT safety guidance on clinical decision
//!   support.
//! - Institute for Safe Medication Practices (ISMP), guidance on CDS alert
//!   design and governance.
//!
//! Topic doc: digital-health-metrics/locales/en-gb-oxendict/topics/clinical-alert-override-rate/index.md

/// The alert override rate: alerts overridden as a percentage of alerts
/// fired.
///
/// Call it once per severity tier or alert type to segment the result — a
/// single blended figure conflates well-justified and unsafe overrides.
///
/// # Arguments
///
/// * `overridden` — alerts the clinician dismissed or overrode (count).
/// * `total_fired` — total alerts fired in the period, or tier (count).
///
/// # Returns
///
/// `Some(percentage)`, or `None` if `total_fired` is zero.
///
/// # Examples
///
/// ```rust
/// use digital_health::clinical_alert_override_rate::override_rate;
///
/// // Worked example, overall: 8,700 / 10,000 × 100 = 87%.
/// let rate = override_rate(8_700.0, 10_000.0).unwrap();
/// assert!((rate - 87.0).abs() < 1e-9);
///
/// assert!(override_rate(1.0, 0.0).is_none());
/// ```
pub fn override_rate(overridden: f64, total_fired: f64) -> Option<f64> {
    if total_fired == 0.0 {
        None
    } else {
        Some(overridden / total_fired * 100.0)
    }
}

/// The documented-override rate: overrides that carry a recorded
/// justification, as a percentage of all overrides.
///
/// A governance measure in its own right, separate from the override rate
/// itself: it says whether clinicians are explaining high-stakes overrides,
/// not merely how often they occur.
///
/// # Arguments
///
/// * `documented` — overrides that carry a recorded reason (count).
/// * `overridden` — total overrides in the period, or tier (count).
///
/// # Returns
///
/// `Some(percentage)`, or `None` if `overridden` is zero.
///
/// # Examples
///
/// ```rust
/// use digital_health::clinical_alert_override_rate::documented_override_rate;
///
/// let rate = documented_override_rate(340.0, 500.0).unwrap();
/// assert!((rate - 68.0).abs() < 1e-9);
/// ```
pub fn documented_override_rate(documented: f64, overridden: f64) -> Option<f64> {
    if overridden == 0.0 {
        None
    } else {
        Some(documented / overridden * 100.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Doc line: "giving an overall override rate of 87%".
    #[test]
    fn worked_example_overall_rate_is_87_percent() {
        let rate = override_rate(8_700.0, 10_000.0).unwrap();
        assert!((rate - 87.0).abs() < 1e-9, "got {rate}");
    }

    // Doc line: "of 500 'contraindicated' alerts, 60 are overridden (12%)".
    #[test]
    fn worked_example_contraindicated_tier_is_12_percent() {
        let rate = override_rate(60.0, 500.0).unwrap();
        assert!((rate - 12.0).abs() < 1e-9, "got {rate}");
    }

    // Doc line: "of 6,000 'moderate' alerts, 5,700 are overridden (95%)".
    #[test]
    fn worked_example_moderate_tier_is_95_percent() {
        let rate = override_rate(5_700.0, 6_000.0).unwrap();
        assert!((rate - 95.0).abs() < 1e-9, "got {rate}");
    }

    #[test]
    fn zero_denominator_returns_none() {
        assert!(override_rate(1.0, 0.0).is_none());
        assert!(documented_override_rate(1.0, 0.0).is_none());
    }
}
